// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI.DataAccess;

#nullable disable

namespace TaskAPI.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240116064050_author_toda_table")]
    partial class author_toda_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Martin Wickramasinghe"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Kumarathunga Munidasa"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Mahagama Sekara"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2024, 1, 16, 12, 10, 49, 799, DateTimeKind.Local).AddTicks(8385),
                            Description = "Description 1",
                            Due = new DateTime(2024, 1, 21, 12, 10, 49, 799, DateTimeKind.Local).AddTicks(8398),
                            Status = 0,
                            Title = "Get books for school"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Created = new DateTime(2024, 1, 16, 12, 10, 49, 799, DateTimeKind.Local).AddTicks(8406),
                            Description = "Description 2",
                            Due = new DateTime(2024, 1, 21, 12, 10, 49, 799, DateTimeKind.Local).AddTicks(8407),
                            Status = 0,
                            Title = "Get books for school2"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Created = new DateTime(2024, 1, 16, 12, 10, 49, 799, DateTimeKind.Local).AddTicks(8408),
                            Description = "Description 3",
                            Due = new DateTime(2024, 1, 21, 12, 10, 49, 799, DateTimeKind.Local).AddTicks(8409),
                            Status = 2,
                            Title = "Get books for school3"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Created = new DateTime(2024, 1, 16, 12, 10, 49, 799, DateTimeKind.Local).AddTicks(8410),
                            Description = "Description 4",
                            Due = new DateTime(2024, 1, 21, 12, 10, 49, 799, DateTimeKind.Local).AddTicks(8411),
                            Status = 0,
                            Title = "Get books for school4"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.HasOne("TaskAPI.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
